config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
#  workdir: ~/.config/dotdrop
dotfiles:
  d_vimrc_desktop:
    dst: ~/.vim
    src: desktop_vimrc
  d_vimrc_server:
    dst: ~/.vim
    src: server_vimrc
profiles:
  desktop:
    dotfiles:
    - d_vimrc_desktop
  server:
    dotfiles:
    - d_vimrc_server
