set all&
set paste

filetype plugin indent on  " Load plugins according to detected filetype.
syntax on

""""i"
inoremap kk <ESC>
let mapleader = " "
map ; <leader>
noremap <Leader>s :w<CR>
noremap <Leader>q :q<CR>
noremap <Leader>x :x<CR>

" Disable paste for using supertab plugin
" set paste
" set paste on the fly
" noremap <leader>p :set paste<CR>
" unset paste on the fly
" noremap <leader>P :set nopaste<CR>
nnoremap <expr> <leader>p &paste =~ '1' ? ':set nopaste<cr>' : ':set paste<cr>'

" jump to next tab
noremap <leader>t gt
" jump to previous tab
noremap <leader>T gT

" set number
"" set adaptive toggle number
nnoremap <expr> <leader>n &number =~# '1' ? ':set nonumber<cr>' : ':set number<cr>'
" set relativenumber
nnoremap <expr> <leader>N &relativenumber =~ '1' ? ':set norelativenumber<cr>' : ':set relativenumber<cr>'

" tabnew
noremap <leader>o :tabnew 

" set wrap on the fly
" set wrap
nnoremap <expr> <leader>w &wrap =~ '1' ? ':set nowrap<cr>' : ':set wrap<cr>'

" Reload config
noremap <leader>r :so ~/.vim/server.vimrc<CR>
" noremap <leader>R :so ~/.vim/vimrc.local<CR>
noremap <leader>R :so ~/.vim/vimrc<CR>

" Make Ctrl-w undoable
inoremap <C-w> <C-g>u<C-w>

