set all&
set paste

filetype plugin indent on  " Load plugins according to detected filetype.
syntax on

set list listchars=tab:❘-,trail:·,extends:»,precedes:«,nbsp:×

set showmode               " Show current mode in command-line.
set showcmd                " Show already typed keys when more are expected.

set splitbelow             " Open new windows below the current window.
set splitright             " Open new windows right of the current window.

set wrapscan               " Searches wrap around end-of-file.
set report      =0         " Always report changed lines.

" set highlight search
set noswapfile " disable the swapfile
set hlsearch " highlight all results
set ignorecase " ignore case in search
set incsearch " show search results as you type

set scrolloff=9

vnoremap < <gv
vnoremap > >gv

set tabstop=4
set autoindent             " Indent according to previous line.
set expandtab              " Use spaces instead of tabs.
set softtabstop =4         " Tab key indents by 4 spaces.
set shiftwidth  =4         " >> indents by 4 spaces.
set shiftround             " >> indents to next multiple of 'shiftwidth'.

""""i"
inoremap kk <ESC>
let mapleader = " "
map ; <leader>
noremap <Leader>s :w<CR>
noremap <Leader>q :q<CR>
noremap <Leader>x :x<CR>

" Disable paste for using supertab plugin
" set paste
" set paste on the fly
" noremap <leader>p :set paste<CR>
" unset paste on the fly
" noremap <leader>P :set nopaste<CR>
nnoremap <expr> <leader>p &paste =~ '1' ? ':set nopaste<cr>' : ':set paste<cr>'

" jump to next tab
noremap <leader>t gt
" jump to previous tab
noremap <leader>T gT

" set number
"" set adaptive toggle number
nnoremap <expr> <leader>n &number =~# '1' ? ':set nonumber<cr>' : ':set number<cr>'
" set relativenumber
nnoremap <expr> <leader>N &relativenumber =~ '1' ? ':set norelativenumber<cr>' : ':set relativenumber<cr>'

" tabnew
noremap <leader>o :tabnew 

" set wrap on the fly
" set wrap
nnoremap <expr> <leader>w &wrap =~ '1' ? ':set nowrap<cr>' : ':set wrap<cr>'

" Reload config
noremap <leader>r :so ~/.vim/server.vimrc<CR>
" noremap <leader>R :so ~/.vim/vimrc.local<CR>
noremap <leader>R :so ~/.vim/vimrc<CR>

" Make Ctrl-w undoable
inoremap <C-w> <C-g>u<C-w>

